#pragma config(Motor,  port1,           M1,            tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           M2,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           M3,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           M4,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Thresh = 10;
int MaxS = 127;
int MaxSL = MaxS*-1;

void Drive () {
	//For each individual side
	if (getJoystickValue(Ch3) > Thresh)
	{
		motor[M1] = MaxS;
		motor[M3] = MaxS;
	}
	if (getJoystickValue(Ch2) > Thresh)
	{
		motor[M2] = MaxS;
		motor[M3] = MaxS;
	}
	if (getJoystickValue(Ch3) < Thresh*-1)
	{
		motor[M1] = MaxSL;
		motor[M3] = MaxSL;
	}
	if (getJoystickValue(Ch2) < Thresh*-1)
	{
		motor[M2] = MaxSL;
		motor[M4] = MaxSL;
	}

	if (getJoystickValue(Ch4) > Thresh)
	{
		motor[M1] = MaxS;
		motor[M2] = MaxS;
		motor[M3] = MaxS;
		motor[M4] = MaxS;
	}
	if (getJoystickValue(Ch4) < Thresh*-1)
	{
		motor[M1] = MaxSL;
		motor[M2] = MaxSL;
		motor[M3] = MaxSL;
		motor[M4] = MaxSL;
	}







}


task main()
{
	while(true)
	{
Drive();
	}
}
